import { LiveClass, LiveStatus, MeetingProvider } from '../types';

export class LiveClassModel implements LiveClass {
  classId: string;
  title: string;
  description: string;
  courseId: string;
  courseName: string;
  moduleId: string;
  moduleTitle: string;
  lessonId: string;
  lessonTitle: string;
  instructorId: string;
  instructorName: string;
  instructorAvatar?: string;
  branch?: string;
  semester?: string;
  year?: string;
  section?: string;
  allowedStudents?: string[];
  meetingProvider: MeetingProvider;
  meetingRoomId: string;
  meetingUrl: string;
  banner?: string;
  thumbnail?: string;
  startTime: string;
  endTime: string;
  duration: number;
  status: LiveStatus;
  isRecordingEnabled: boolean;
  isQuizEnabled: boolean;
  isPollEnabled: boolean;
  isChatEnabled: boolean;
  isAttendanceEnabled: boolean;
  resourceDownloadEnabled?: boolean;
  certificateEligible: boolean;
  maxParticipants: number;
  tags: string[];
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  notesUrl?: string;
  recordingUrl?: string;
  pinnedMessage?: string;
  isChatMuted?: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;

  constructor(data: LiveClass) {
    this.classId = data.classId;
    this.title = data.title;
    this.description = data.description;
    this.courseId = data.courseId;
    this.courseName = data.courseName;
    this.moduleId = data.moduleId;
    this.moduleTitle = data.moduleTitle;
    this.lessonId = data.lessonId;
    this.lessonTitle = data.lessonTitle;
    this.instructorId = data.instructorId;
    this.instructorName = data.instructorName;
    this.instructorAvatar = data.instructorAvatar;
    this.branch = data.branch;
    this.semester = data.semester;
    this.year = data.year;
    this.section = data.section;
    this.allowedStudents = data.allowedStudents;
    this.meetingProvider = data.meetingProvider || MeetingProvider.JITSI;
    this.meetingRoomId = data.meetingRoomId;
    this.meetingUrl = data.meetingUrl;
    this.banner = data.banner;
    this.thumbnail = data.thumbnail;
    this.startTime = data.startTime;
    this.endTime = data.endTime;
    this.duration = data.duration;
    this.status = data.status || LiveStatus.Scheduled;
    this.isRecordingEnabled = data.isRecordingEnabled;
    this.isQuizEnabled = data.isQuizEnabled;
    this.isPollEnabled = data.isPollEnabled;
    this.isChatEnabled = data.isChatEnabled;
    this.isAttendanceEnabled = data.isAttendanceEnabled;
    this.resourceDownloadEnabled = data.resourceDownloadEnabled;
    this.certificateEligible = data.certificateEligible;
    this.maxParticipants = data.maxParticipants || 100;
    this.tags = data.tags || [];
    this.difficulty = data.difficulty || 'Intermediate';
    this.notesUrl = data.notesUrl;
    this.recordingUrl = data.recordingUrl;
    this.pinnedMessage = data.pinnedMessage;
    this.isChatMuted = data.isChatMuted;
    this.createdBy = data.createdBy;
    this.createdAt = data.createdAt || new Date().toISOString();
    this.updatedAt = data.updatedAt || new Date().toISOString();
  }
}
