import React, { useState, useEffect, useMemo, useRef } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { useCourses } from '@/contexts/CourseContext';
import type { ModuleItem, LearningUnitItem } from '@/contexts/CourseContext';
import { loadStaticCourseModules } from '@/contexts/CourseContext';
import {
  Folder,
  FileText,
  Layers,
  ChevronRight,
  ChevronDown,
  Plus,
  Trash2,
  Copy,
  Eye,
  Search,
  FileCode,
  Save,
  ChevronUp,
  Clock,
  BookOpen,
  AlertTriangle,
  GripVertical,
  Sparkles
} from 'lucide-react';
import { toast } from 'sonner';
import {
  ContentService,
  LessonEditorService
} from '@/services/contentManagementService';
import type { ResourceItem } from '@/services/contentManagementService';
import { sanitizeAdminInput, sanitizeMarkdownContent } from '@/utils/adminDataSanitizer';
import { MarkdownContent } from '@/components/learning/MarkdownContent';
import { aiAutofillService } from '@/services/aiAutofillService';

// Initialize services
const contentService = new ContentService();
const editorService = new LessonEditorService();

// Calculate estimated reading time (~200 words per minute)
function calculateEstimatedReadMinutes(text?: string): number {
  if (!text) return 3;
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(words / 200));
}

function countWords(text?: string): number {
  if (!text) return 0;
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function formatDate(dateVal?: string | number | Date): string {
  if (!dateVal) return 'Today';
  try {
    const d = new Date(dateVal);
    if (isNaN(d.getTime())) return 'Recently';
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return 'Recently';
  }
}

export const AdminContentManagement: React.FC = () => {
  const { courses, updateCourse } = useCourses();
  const [searchParams, setSearchParams] = useSearchParams();

  // Active state selections
  const [selectedCourseId, setSelectedCourseId] = useState<string | number>('');
  const [selectedLesson, setSelectedLesson] = useState<LearningUnitItem | null>(null);
  const [activeModuleId, setActiveModuleId] = useState<string | null>(null);
  const [activeTopicId, setActiveTopicId] = useState<string | null>(null);

  // Dirty state tracking for unsaved changes guard
  const [isDirty, setIsDirty] = useState<boolean>(false);
  const [showDiscardModal, setShowDiscardModal] = useState<boolean>(false);
  const [pendingSelection, setPendingSelection] = useState<{ lesson: LearningUnitItem; mId: string; tId: string } | null>(null);

  // Drag and drop reordering state
  const [draggedLessonInfo, setDraggedLessonInfo] = useState<{ lessonId: string; sourceModId: string; sourceTopId: string } | null>(null);
  const [dragOverLessonId, setDragOverLessonId] = useState<string | null>(null);
  const [dragOverModId, setDragOverModId] = useState<string | null>(null);

  // AI Lesson Autofill State
  const [isAutofillingLesson, setIsAutofillingLesson] = useState(false);

  const handleAiAutofillLesson = async () => {
    if (!selectedLesson) return;
    if (!selectedLesson.title || selectedLesson.title.trim().length < 3) {
      toast.error('Please enter a lesson title with at least 3 characters first.');
      return;
    }

    setIsAutofillingLesson(true);
    try {
      const result = await aiAutofillService.autofillLesson({
        lessonTitle: selectedLesson.title.trim(),
        courseTitle: activeCourse?.title,
        category: activeCourse?.category,
        level: activeCourse?.level
      });

      handleInputChange('readingContent', result.content);
      handleInputChange('estimatedReadMinutes' as any, result.estimatedReadMinutes);
      setActiveTab('reading');
      toast.success('✨ Lesson content generated by AI! Review and edit in the live split preview before saving.');
    } catch (err: any) {
      toast.error(err.message || 'Autofill failed — please try again or write manually.');
    } finally {
      setIsAutofillingLesson(false);
    }
  };

  // Markdown Preview Mode: 'split' | 'editor' | 'preview'
  const [previewMode, setPreviewMode] = useState<'split' | 'editor' | 'preview'>('split');

  // Expanded syllabus nodes mapping
  const [expandedModules, setExpandedModules] = useState<Record<string, boolean>>({});

  // Tree search filter
  const [searchQuery, setSearchQuery] = useState('');

  // Editor Tabs
  const [activeTab, setActiveTab] = useState<'reading' | 'overview' | 'video' | 'resources' | 'quiz' | 'assignment' | 'practice-lab' | 'ai' | 'settings'>('reading');

  // Save Status
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved'>('idle');

  // New module creation toggle inside lesson editor
  const [isCreatingNewMod, setIsCreatingNewMod] = useState(false);
  const [newModTitleInput, setNewModTitleInput] = useState('');

  // New resource state helpers
  const [newResourceName, setNewResourceName] = useState('');
  const [newResourceCat, setNewResourceCat] = useState<'PDF' | 'DOCX' | 'ZIP' | 'Source Code' | 'External Link'>('PDF');

  // Textarea ref for markdown toolbar insertions
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Find active course record
  const activeCourse = courses.find(c => String(c.id) === String(selectedCourseId)) || courses[0];

  // Sync URL search params with active course
  useEffect(() => {
    const qCourseId = searchParams.get('courseId');
    if (qCourseId && courses.length > 0) {
      const matched = courses.find(c => String(c.id) === String(qCourseId) || (c as any).slug === qCourseId);
      if (matched) {
        setSelectedCourseId(matched.id);
        return;
      }
    }
    if (courses.length > 0 && !selectedCourseId) {
      setSelectedCourseId(courses[0].id);
    }
  }, [courses, searchParams]);

  // Dynamic fallback module loader for courses that have empty modules
  useEffect(() => {
    if (activeCourse && (!activeCourse.modules || activeCourse.modules.length === 0)) {
      loadStaticCourseModules(activeCourse.id).then(mods => {
        if (mods && mods.length > 0) {
          updateCourse(activeCourse.id, { modules: mods });
        }
      }).catch(() => {});
    }
  }, [activeCourse?.id]);

  // Automatically expand all modules on course change
  useEffect(() => {
    if (activeCourse?.modules) {
      const expM: Record<string, boolean> = {};
      activeCourse.modules.forEach(m => {
        expM[m.id] = true;
      });
      setExpandedModules(expM);

      // Select first lesson if none selected
      if (!selectedLesson && activeCourse.modules[0]?.topics?.[0]?.learningUnits?.[0]) {
        const firstMod = activeCourse.modules[0];
        const firstTop = firstMod.topics[0];
        const firstUnit = firstTop.learningUnits[0];
        setSelectedLesson({ ...firstUnit });
        setActiveModuleId(firstMod.id);
        setActiveTopicId(firstTop.id);
        setIsDirty(false);
      }
    }
  }, [activeCourse?.id]);

  // Compute Course-Wide Statistics
  const courseStats = useMemo(() => {
    if (!activeCourse || !activeCourse.modules) {
      return { totalModules: 0, totalLessons: 0, totalReadMinutes: 0 };
    }
    let lessonsCount = 0;
    let readMinutes = 0;
    activeCourse.modules.forEach(m => {
      m.topics?.forEach(t => {
        t.learningUnits?.forEach(u => {
          lessonsCount++;
          readMinutes += calculateEstimatedReadMinutes(u.readingContent);
        });
      });
    });
    return {
      totalModules: activeCourse.modules.length,
      totalLessons: lessonsCount,
      totalReadMinutes: readMinutes,
    };
  }, [activeCourse]);

  // Handle Lesson Selection with Unsaved Changes Guard
  const handleSelectLesson = (lesson: LearningUnitItem, mId: string, tId: string) => {
    if (isDirty) {
      setPendingSelection({ lesson, mId, tId });
      setShowDiscardModal(true);
      return;
    }
    setSelectedLesson({ ...lesson });
    setActiveModuleId(mId);
    setActiveTopicId(tId);
    setIsDirty(false);
  };

  const confirmDiscardChanges = () => {
    if (pendingSelection) {
      setSelectedLesson({ ...pendingSelection.lesson });
      setActiveModuleId(pendingSelection.mId);
      setActiveTopicId(pendingSelection.tId);
      setPendingSelection(null);
    }
    setIsDirty(false);
    setShowDiscardModal(false);
  };

  // Helper to commit edits to context and Firestore + Cache Invalidation
  const saveLessonEdits = (updatedLesson: LearningUnitItem) => {
    if (!activeCourse || !activeModuleId || !activeTopicId) return;

    const readMins = calculateEstimatedReadMinutes(updatedLesson.readingContent);
    const nowIso = new Date().toISOString();
    const sanitized: LearningUnitItem = {
      ...updatedLesson,
      title: sanitizeAdminInput(updatedLesson.title),
      description: sanitizeAdminInput(updatedLesson.description),
      duration: updatedLesson.duration || `${readMins} mins`,
      readingContent: updatedLesson.readingContent ? sanitizeMarkdownContent(updatedLesson.readingContent) : updatedLesson.readingContent,
      assignmentInstructions: updatedLesson.assignmentInstructions ? sanitizeMarkdownContent(updatedLesson.assignmentInstructions) : updatedLesson.assignmentInstructions,
      videoUrl: sanitizeAdminInput(updatedLesson.videoUrl),
      lastSavedAt: nowIso,
    };

    const nextModules = activeCourse.modules ? activeCourse.modules.map(m => {
      if (m.id !== activeModuleId) return m;

      const nextTopics = m.topics.map(t => {
        if (t.id !== activeTopicId) return t;

        const nextUnits = t.learningUnits.map(u => {
          if (u.id === sanitized.id) {
            return sanitized;
          }
          return u;
        });
        return { ...t, learningUnits: nextUnits };
      });
      return { ...m, topics: nextTopics };
    }) : [];

    updateCourse(activeCourse.id, { modules: nextModules });
    
    // Invalidate local client storage cache for immediate student sync
    try {
      localStorage.removeItem(`course_cache_${activeCourse.id}`);
      localStorage.removeItem(`lesson_cache_${sanitized.id}`);
    } catch { /* noop */ }

    setIsDirty(false);
    setSaveStatus('saved');
    setTimeout(() => setSaveStatus('idle'), 2500);
  };

  // Explicit Save Button Trigger
  const handleManualSave = () => {
    if (!selectedLesson) return;
    if (!selectedLesson.title.trim()) {
      toast.error('Lesson title cannot be empty.');
      return;
    }
    if (!selectedLesson.readingContent?.trim()) {
      toast.error('Lesson content cannot be empty.');
      return;
    }
    setSaveStatus('saving');
    saveLessonEdits(selectedLesson);
    toast.success(`Saved "${selectedLesson.title}" successfully!`);
  };

  // Input change listener
  const handleInputChange = (field: keyof LearningUnitItem, value: any) => {
    if (!selectedLesson) return;
    const updated = { ...selectedLesson, [field]: value };
    setSelectedLesson(updated);
    setIsDirty(true);

    editorService.triggerAutosave(() => {
      saveLessonEdits(updated);
    }, setSaveStatus);
  };

  // Move Lesson to a Different Module
  const handleMoveLessonToModule = (newModId: string) => {
    if (!activeCourse || !activeCourse.modules || !selectedLesson || !activeModuleId || !activeTopicId) return;
    if (newModId === activeModuleId) return;

    const targetModule = activeCourse.modules.find(m => m.id === newModId);
    if (!targetModule) return;
    const targetTopic = targetModule.topics?.[0];
    if (!targetTopic) return;

    const lessonToMove = { ...selectedLesson };

    const updated = activeCourse.modules.map(m => {
      let nextTopics = m.topics.map(t => {
        let units = [...t.learningUnits];
        if (m.id === activeModuleId && t.id === activeTopicId) {
          units = units.filter(u => u.id !== lessonToMove.id);
        }
        if (m.id === newModId && t.id === targetTopic.id) {
          units.push(lessonToMove);
        }
        return {
          ...t,
          learningUnits: units.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 }))
        };
      });
      return { ...m, topics: nextTopics };
    });

    updateCourse(activeCourse.id, { modules: updated });
    setActiveModuleId(newModId);
    setActiveTopicId(targetTopic.id);
    toast.success(`Moved lesson to "${targetModule.title}".`);
  };

  // Create new module and move current lesson into it
  const handleCreateModuleAndMove = () => {
    if (!newModTitleInput.trim() || !activeCourse || !selectedLesson || !activeModuleId || !activeTopicId) {
      toast.error('Please enter a module title.');
      return;
    }
    const newModId = `mod_${Date.now()}`;
    const newTopicId = `top_${Date.now()}`;
    const lessonToMove = { ...selectedLesson };

    const newMod: ModuleItem = {
      id: newModId,
      title: newModTitleInput.trim(),
      description: 'Module topics and materials.',
      duration: '2 Hours',
      topics: [
        {
          id: newTopicId,
          title: 'Topic 1: Overview',
          description: 'Topic introduction',
          estimatedDuration: '30 mins',
          learningUnits: [lessonToMove]
        }
      ]
    };

    const updated = (activeCourse.modules || []).map(m => {
      if (m.id !== activeModuleId) return m;
      const nextTopics = m.topics.map(t => {
        if (t.id !== activeTopicId) return t;
        const filtered = t.learningUnits.filter(u => u.id !== lessonToMove.id);
        return {
          ...t,
          learningUnits: filtered.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 }))
        };
      });
      return { ...m, topics: nextTopics };
    });

    updated.push(newMod);
    updateCourse(activeCourse.id, { modules: updated });
    setActiveModuleId(newModId);
    setActiveTopicId(newTopicId);
    setIsCreatingNewMod(false);
    setNewModTitleInput('');
    toast.success(`Created "${newMod.title}" and moved lesson.`);
  };

  // HTML5 Drag and Drop Handlers
  const handleDragStart = (e: React.DragEvent, lessonId: string, mId: string, tId: string) => {
    setDraggedLessonInfo({ lessonId, sourceModId: mId, sourceTopId: tId });
    e.dataTransfer.setData('text/plain', lessonId);
    e.dataTransfer.effectAllowed = 'move';
  };

  const handleDropOnLesson = (e: React.DragEvent, targetLessonId: string, targetModId: string, targetTopId: string) => {
    e.preventDefault();
    e.stopPropagation();
    setDragOverLessonId(null);
    setDragOverModId(null);
    if (!draggedLessonInfo || !activeCourse || !activeCourse.modules) return;
    const { lessonId: srcId, sourceModId: srcModId, sourceTopId: srcTopId } = draggedLessonInfo;
    if (srcId === targetLessonId) return;

    let draggedLesson: LearningUnitItem | null = null;
    activeCourse.modules.forEach(m => {
      m.topics?.forEach(t => {
        const found = t.learningUnits.find(u => u.id === srcId);
        if (found) draggedLesson = found;
      });
    });
    if (!draggedLesson) return;

    const updated = activeCourse.modules.map(m => {
      let nextTopics = m.topics.map(t => {
        let units = [...t.learningUnits];
        if (m.id === srcModId && t.id === srcTopId) {
          units = units.filter(u => u.id !== srcId);
        }
        if (m.id === targetModId && t.id === targetTopId) {
          const targetIndex = units.findIndex(u => u.id === targetLessonId);
          if (targetIndex !== -1) {
            units.splice(targetIndex, 0, draggedLesson!);
          } else {
            units.push(draggedLesson!);
          }
        }
        return {
          ...t,
          learningUnits: units.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 }))
        };
      });
      return { ...m, topics: nextTopics };
    });

    updateCourse(activeCourse.id, { modules: updated });
    setDraggedLessonInfo(null);
    toast.success('Lesson reordered successfully.');
  };

  const handleDropOnModule = (e: React.DragEvent, targetModId: string, targetTopId: string) => {
    e.preventDefault();
    e.stopPropagation();
    setDragOverLessonId(null);
    setDragOverModId(null);
    if (!draggedLessonInfo || !activeCourse || !activeCourse.modules) return;
    const { lessonId: srcId, sourceModId: srcModId, sourceTopId: srcTopId } = draggedLessonInfo;
    if (srcModId === targetModId) return;

    let draggedLesson: LearningUnitItem | null = null;
    activeCourse.modules.forEach(m => {
      m.topics?.forEach(t => {
        const found = t.learningUnits.find(u => u.id === srcId);
        if (found) draggedLesson = found;
      });
    });
    if (!draggedLesson) return;

    const updated = activeCourse.modules.map(m => {
      let nextTopics = m.topics.map(t => {
        let units = [...t.learningUnits];
        if (m.id === srcModId && t.id === srcTopId) {
          units = units.filter(u => u.id !== srcId);
        }
        if (m.id === targetModId && t.id === targetTopId) {
          units.push(draggedLesson!);
        }
        return {
          ...t,
          learningUnits: units.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 }))
        };
      });
      return { ...m, topics: nextTopics };
    });

    updateCourse(activeCourse.id, { modules: updated });
    setDraggedLessonInfo(null);
    toast.success('Moved lesson to new module.');
  };

  // Insert Markdown helper
  const insertMarkdown = (syntaxType: string) => {
    if (!selectedLesson) return;
    const current = selectedLesson.readingContent || '';
    const textarea = textareaRef.current;
    
    let insertion = '';
    switch (syntaxType) {
      case 'h2':
        insertion = '\n## New Section Heading\n';
        break;
      case 'h3':
        insertion = '\n### Subsection Title\n';
        break;
      case 'bold':
        insertion = '**bold text**';
        break;
      case 'italic':
        insertion = '*italic text*';
        break;
      case 'code-js':
        insertion = '\n```javascript\n// JavaScript code example\nconst message = "Hello KaizenQ!";\nconsole.log(message);\n```\n';
        break;
      case 'code-py':
        insertion = '\n```python\n# Python code example\ndef main():\n    print("Hello KaizenQ!")\n```\n';
        break;
      case 'code-sql':
        insertion = '\n```sql\n-- SQL Query example\nSELECT id, title, category FROM courses WHERE status = \'published\';\n```\n';
        break;
      case 'tip':
        insertion = '\n> 💡 **Tip:** Always use structured markdown formatting and code examples to provide maximum clarity.\n';
        break;
      case 'note':
        insertion = '\n> 📌 **Note:** This concept is essential for real-world production system design.\n';
        break;
      case 'warning':
        insertion = '\n> ⚠️ **Warning:** Be cautious of state mutability and memory leaks in production.\n';
        break;
      case 'list':
        insertion = '\n- First key point\n- Second key point\n- Third key point\n';
        break;
      case 'numlist':
        insertion = '\n1. First sequential step\n2. Second sequential step\n3. Third sequential step\n';
        break;
      case 'table':
        insertion = '\n| Concept | Description | Complexity |\n|---|---|---|\n| Linear Scan | Scans each element | $O(N)$ |\n| Binary Search | Halves search space | $O(\\log N)$ |\n';
        break;
      default:
        insertion = '\n';
    }

    if (textarea) {
      const start = textarea.selectionStart;
      const end = textarea.selectionEnd;
      const nextContent = current.substring(0, start) + insertion + current.substring(end);
      handleInputChange('readingContent', nextContent);
      setTimeout(() => {
        textarea.focus();
        textarea.setSelectionRange(start + insertion.length, start + insertion.length);
      }, 50);
    } else {
      handleInputChange('readingContent', current + insertion);
    }
  };

  // Reordering actions with contiguous index normalization
  const moveLesson = (mId: string, tId: string, lessonId: string, direction: 'up' | 'down') => {
    if (!activeCourse || !activeCourse.modules) return;
    const updated = activeCourse.modules.map(m => {
      if (m.id === mId) {
        const nextTopics = m.topics.map(t => {
          if (t.id === tId) {
            const reordered = contentService.reorderLesson(t.learningUnits, lessonId, direction);
            return {
              ...t,
              learningUnits: reordered.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 }))
            };
          }
          return t;
        });
        return { ...m, topics: nextTopics };
      }
      return m;
    });
    updateCourse(activeCourse.id, { modules: updated });
    toast.success('Lesson position updated.');
  };

  // Node deletion with automatic contiguous re-sequencing
  const deleteLesson = (mId: string, tId: string, lessonId: string, lessonTitle: string) => {
    if (!window.confirm(`Delete "${lessonTitle}"? This cannot be undone.`)) {
      return;
    }
    if (!activeCourse || !activeCourse.modules) return;
    const updated = activeCourse.modules.map(m => {
      if (m.id === mId) {
        const nextTopics = m.topics.map(t => {
          if (t.id === tId) {
            const filtered = t.learningUnits.filter(u => u.id !== lessonId);
            return {
              ...t,
              learningUnits: filtered.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 }))
            };
          }
          return t;
        });
        return { ...m, topics: nextTopics };
      }
      return m;
    });
    updateCourse(activeCourse.id, { modules: updated });
    if (selectedLesson?.id === lessonId) {
      setSelectedLesson(null);
      setIsDirty(false);
    }
    toast.success(`Deleted lesson "${lessonTitle}". Remaining lessons re-sequenced.`);
  };

  // Duplicate lesson
  const duplicateLesson = (mId: string, tId: string, lesson: LearningUnitItem) => {
    if (!activeCourse || !activeCourse.modules) return;
    const duplicated: LearningUnitItem = {
      ...lesson,
      id: `copy_${Date.now()}_${lesson.id}`,
      title: `${lesson.title} (Copy)`,
      order: (lesson.order || 1) + 1,
      orderIndex: (lesson.orderIndex || 1) + 1,
      lastSavedAt: new Date().toISOString()
    };

    const updated = activeCourse.modules.map(m => {
      if (m.id === mId) {
        const nextTopics = m.topics.map(t => {
          if (t.id === tId) {
            const list = [...t.learningUnits, duplicated];
            return { ...t, learningUnits: list.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 })) };
          }
          return t;
        });
        return { ...m, topics: nextTopics };
      }
      return m;
    });
    updateCourse(activeCourse.id, { modules: updated });
    toast.success('Lesson duplicated successfully.');
  };

  // Add new lesson
  const addLessonNode = (mId: string, tId: string) => {
    if (!activeCourse || !activeCourse.modules) return;
    const targetModule = activeCourse.modules.find(m => m.id === mId);
    const existingCount = targetModule?.topics?.flatMap(t => t.learningUnits).length || 0;
    const newLessonId = `lesson_${Date.now()}`;
    const newLesson: LearningUnitItem = {
      id: newLessonId,
      title: `Lesson ${existingCount + 1}: New Educational Topic`,
      description: 'Comprehensive lesson notes and explanations.',
      duration: '15 mins',
      type: 'Reading',
      order: existingCount + 1,
      orderIndex: existingCount + 1,
      lastSavedAt: new Date().toISOString(),
      readingContent: `# Lesson Title\n\n## Overview\nProvide a clear overview of the lesson objectives here.\n\n## Core Concepts\nExplain the foundational concepts in detail.\n\n\`\`\`javascript\n// Code example\nconsole.log("Welcome to KaizenQ!");\n\`\`\`\n\n> 💡 **Tip:** Add actionable advice for students.\n`
    };

    const updated = activeCourse.modules.map(m => {
      if (m.id === mId) {
        const nextTopics = m.topics.map(t => {
          if (t.id === tId) {
            const list = [...t.learningUnits, newLesson];
            return { ...t, learningUnits: list.map((u, idx) => ({ ...u, order: idx + 1, orderIndex: idx + 1 })) };
          }
          return t;
        });
        return { ...m, topics: nextTopics };
      }
      return m;
    });
    updateCourse(activeCourse.id, { modules: updated });
    setSelectedLesson(newLesson);
    setActiveModuleId(mId);
    setActiveTopicId(tId);
    setIsDirty(false);
    toast.success('Added new Lesson. Ready to edit!');
  };

  // Add new module
  const addModuleNode = () => {
    if (!activeCourse) return;
    const newModId = `mod_${Date.now()}`;
    const newTopicId = `top_${Date.now()}`;
    const newMod: ModuleItem = {
      id: newModId,
      title: `Module ${(activeCourse.modules?.length || 0) + 1}: New Curriculum Module`,
      description: 'Module overview and topics.',
      duration: '3 Hours',
      topics: [
        {
          id: newTopicId,
          title: 'Topic 1: Foundations',
          description: 'Topic introduction',
          estimatedDuration: '45 mins',
          learningUnits: [
            {
              id: `lesson_${Date.now()}`,
              title: 'Module Introduction & Notes',
              description: 'Introductory notes.',
              duration: '15 mins',
              type: 'Reading',
              order: 1,
              orderIndex: 1,
              lastSavedAt: new Date().toISOString(),
              readingContent: '# Module Introduction\n\nWelcome to this module!'
            }
          ]
        }
      ]
    };
    const updated = [...(activeCourse.modules || []), newMod];
    updateCourse(activeCourse.id, { modules: updated });
    toast.success('Added new Module.');
  };

  // Attached resources handlers
  const addResourceToLesson = () => {
    if (!selectedLesson || !newResourceName.trim()) {
      toast.error('Please enter a resource file name.');
      return;
    }
    const newRes: ResourceItem = {
      id: `res_${Date.now()}`,
      name: newResourceName.trim(),
      description: `Resource attached to ${selectedLesson.title}`,
      category: newResourceCat,
      fileSize: '1.5 MB',
      downloadPermission: true,
      fileUrl: '#'
    };
    const currentRes = (selectedLesson as any).resources || [];
    handleInputChange('resources' as any, [...currentRes, newRes]);
    setNewResourceName('');
    toast.success('Resource attached.');
  };

  const deleteResource = (resId: string) => {
    if (!selectedLesson) return;
    const currentRes = (selectedLesson as any).resources || [];
    handleInputChange('resources' as any, currentRes.filter((r: any) => r.id !== resId));
    toast.success('Resource removed.');
  };

  // Calculate live word count and read time
  const currentWords = countWords(selectedLesson?.readingContent);
  const currentReadTime = calculateEstimatedReadMinutes(selectedLesson?.readingContent);

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)] max-w-[1700px] mx-auto p-3 sm:p-5 space-y-4">
      
      {/* 1. TOP HEADER & COURSE SELECTOR BAR */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 bg-white/95 dark:bg-slate-900/95 border border-slate-200/80 dark:border-slate-800 rounded-3xl p-4 sm:p-5 shadow-xs backdrop-blur-md">
        
        {/* Course Dropdown & Meta */}
        <div className="flex flex-wrap items-center gap-3.5 min-w-0">
          <div className="w-10 h-10 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-100 dark:border-indigo-800 flex items-center justify-center text-indigo-600 dark:text-indigo-400 shrink-0">
            <Layers className="w-5 h-5" />
          </div>

          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400 dark:text-slate-500 font-heading">
                Course Content Studio
              </span>
              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 border border-emerald-200/50 dark:border-emerald-800/50">
                Live Sync
              </span>
            </div>

            <div className="flex items-center gap-2 mt-0.5">
              <select
                value={selectedCourseId}
                onChange={(e) => {
                  setSelectedCourseId(e.target.value);
                  setSearchParams({ courseId: String(e.target.value) });
                }}
                className="bg-transparent text-slate-900 dark:text-white font-heading font-extrabold text-base sm:text-lg border-none focus:outline-hidden cursor-pointer hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors pr-6"
              >
                {courses.map((c) => (
                  <option key={c.id} value={c.id} className="dark:bg-slate-900 text-slate-900 dark:text-white">
                    {c.title} ({c.level || 'All Levels'})
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>

        {/* Course Summary Metrics Badges */}
        <div className="flex flex-wrap items-center gap-2 sm:gap-3 text-xs font-semibold select-none">
          <div className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-700 dark:text-slate-300">
            <BookOpen className="w-4 h-4 text-indigo-500" />
            <span><strong>{courseStats.totalModules}</strong> Modules</span>
          </div>

          <div className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-700 dark:text-slate-300">
            <FileText className="w-4 h-4 text-sky-500" />
            <span><strong>{courseStats.totalLessons}</strong> Lessons in Course</span>
          </div>

          <div className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-700 dark:text-slate-300">
            <Clock className="w-4 h-4 text-amber-500" />
            <span><strong>~{Math.round(courseStats.totalReadMinutes / 60)}h {courseStats.totalReadMinutes % 60}m</strong> Total Duration</span>
          </div>

          <Link
            to={`/course/${activeCourse?.slug || activeCourse?.id || ''}`}
            target="_blank"
            className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-50 hover:bg-indigo-100 dark:bg-indigo-950/50 dark:hover:bg-indigo-900/50 text-indigo-600 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800/60 rounded-xl font-bold transition-colors cursor-pointer"
          >
            <Eye className="w-3.5 h-3.5" />
            <span>Preview Student View</span>
          </Link>
        </div>
      </div>

      {/* 2. TWO-COLUMN WORKSPACE: LEFT TREE EXPLORER & RIGHT LESSON EDITOR */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 flex-1 min-h-0">
        
        {/* LEFT COLUMN: MODULE & LESSON HIERARCHY TREE WITH DRAG & DROP */}
        <div className="lg:col-span-4 bg-white/95 dark:bg-slate-900/95 border border-slate-200/80 dark:border-slate-800 rounded-3xl p-4 flex flex-col shadow-xs overflow-hidden">
          
          {/* Header & Search */}
          <div className="space-y-3 pb-3 border-b border-slate-100 dark:border-slate-800 shrink-0 select-none">
            <div className="flex items-center justify-between">
              <h3 className="font-heading font-extrabold text-sm text-slate-800 dark:text-slate-200 flex items-center gap-2">
                <Folder className="w-4 h-4 text-indigo-500" />
                <span>Curriculum Outline</span>
              </h3>

              <button
                onClick={addModuleNode}
                className="py-1 px-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-[11px] font-bold flex items-center gap-1 cursor-pointer transition-all shadow-xs"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add Module</span>
              </button>
            </div>

            {/* Filter Search */}
            <div className="relative">
              <Search className="w-3.5 h-3.5 absolute left-3 top-2.5 text-slate-400" />
              <input
                type="text"
                placeholder="Search lessons or topics..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-slate-50 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800 rounded-xl pl-8 pr-3 py-1.5 text-xs text-slate-900 dark:text-white focus:outline-hidden focus:border-indigo-500"
              />
            </div>
          </div>

          {/* Scrollable Tree List with Drag and Drop Support */}
          <div className="flex-1 overflow-y-auto space-y-2.5 pt-3 pr-1">
            {(!activeCourse?.modules || activeCourse.modules.length === 0) ? (
              <div className="text-center py-10 space-y-2">
                <p className="text-xs text-slate-400 dark:text-slate-500">No modules in this course yet.</p>
                <button
                  onClick={addModuleNode}
                  className="text-xs text-indigo-600 dark:text-indigo-400 font-bold hover:underline"
                >
                  Create First Module
                </button>
              </div>
            ) : (
              activeCourse.modules.map((module) => {
                const isModExpanded = expandedModules[module.id] !== false;
                const allUnitsInModule = module.topics?.flatMap(t => t.learningUnits) || [];
                const firstTopic = module.topics?.[0];
                const isDragOverMod = dragOverModId === module.id;

                return (
                  <div
                    key={module.id}
                    onDragOver={(e) => {
                      e.preventDefault();
                      setDragOverModId(module.id);
                    }}
                    onDragLeave={() => setDragOverModId(null)}
                    onDrop={(e) => firstTopic && handleDropOnModule(e, module.id, firstTopic.id)}
                    className={`border rounded-2xl overflow-hidden transition-all ${
                      isDragOverMod
                        ? 'border-indigo-500 bg-indigo-50/40 dark:bg-indigo-950/40'
                        : 'border-slate-200/60 dark:border-slate-800/80 bg-slate-50/40 dark:bg-slate-950/40'
                    }`}
                  >
                    
                    {/* Module Accordion Header */}
                    <div
                      onClick={() => setExpandedModules(prev => ({ ...prev, [module.id]: !isModExpanded }))}
                      className="p-3 bg-slate-100/70 dark:bg-slate-900/80 flex items-center justify-between gap-2 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-900 transition-colors select-none"
                    >
                      <div className="flex items-center gap-2 min-w-0">
                        {isModExpanded ? <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" /> : <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />}
                        <span className="font-heading font-extrabold text-xs text-slate-800 dark:text-slate-200 truncate">
                          {module.title}
                        </span>
                      </div>

                      <div className="flex items-center gap-1 shrink-0" onClick={e => e.stopPropagation()}>
                        <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 px-1.5 py-0.5 bg-white dark:bg-slate-950 rounded-md border border-slate-200 dark:border-slate-800">
                          {allUnitsInModule.length}
                        </span>

                        <button
                          onClick={() => {
                            const firstTopicId = module.topics?.[0]?.id || `top_${Date.now()}`;
                            addLessonNode(module.id, firstTopicId);
                          }}
                          className="p-1 hover:bg-white dark:hover:bg-slate-800 text-indigo-600 dark:text-indigo-400 rounded-md cursor-pointer"
                          title="Add Lesson to Module"
                        >
                          <Plus className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>

                    {/* Lessons inside Module */}
                    {isModExpanded && (
                      <div className="p-2 space-y-1.5">
                        {module.topics?.map(topic => (
                          <div key={topic.id} className="space-y-1">
                            {topic.learningUnits
                              .filter(u => !searchQuery || u.title.toLowerCase().includes(searchQuery.toLowerCase()))
                              .map((unit, uIdx) => {
                                const isSelected = selectedLesson?.id === unit.id;
                                const readMins = calculateEstimatedReadMinutes(unit.readingContent);
                                const isDragOverThis = dragOverLessonId === unit.id;

                                return (
                                  <div
                                    key={unit.id}
                                    draggable
                                    onDragStart={(e) => handleDragStart(e, unit.id, module.id, topic.id)}
                                    onDragOver={(e) => {
                                      e.preventDefault();
                                      setDragOverLessonId(unit.id);
                                    }}
                                    onDragLeave={() => setDragOverLessonId(null)}
                                    onDrop={(e) => handleDropOnLesson(e, unit.id, module.id, topic.id)}
                                    onClick={() => handleSelectLesson(unit, module.id, topic.id)}
                                    className={`group flex items-center justify-between gap-2 p-2.5 rounded-xl cursor-pointer transition-all ${
                                      isDragOverThis
                                        ? 'border-2 border-indigo-500 bg-indigo-50 dark:bg-indigo-950'
                                        : isSelected
                                        ? 'bg-indigo-600 text-white shadow-xs'
                                        : 'bg-white dark:bg-slate-900/90 text-slate-700 dark:text-slate-300 hover:bg-indigo-50/60 dark:hover:bg-slate-800 border border-slate-150 dark:border-slate-800/60'
                                    }`}
                                  >
                                    <div className="flex items-center gap-2 min-w-0">
                                      <GripVertical className={`w-3.5 h-3.5 shrink-0 cursor-grab active:cursor-grabbing ${
                                        isSelected ? 'text-indigo-300' : 'text-slate-400'
                                      }`} />

                                      <span className={`text-[10px] font-mono font-bold px-1.5 py-0.5 rounded shrink-0 ${
                                        isSelected ? 'bg-indigo-700 text-indigo-100' : 'bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400'
                                      }`}>
                                        #{unit.order || uIdx + 1}
                                      </span>

                                      <div className="min-w-0">
                                        <h5 className="font-bold text-xs truncate leading-snug">
                                          {unit.title}
                                        </h5>
                                        <div className="flex items-center gap-2 mt-0.5 text-[10px] opacity-80">
                                          <span>📖 ~{readMins}m</span>
                                          <span>•</span>
                                          <span className="truncate">{formatDate(unit.lastSavedAt)}</span>
                                        </div>
                                      </div>
                                    </div>

                                    {/* Action Buttons */}
                                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity shrink-0" onClick={e => e.stopPropagation()}>
                                      <button
                                        onClick={() => moveLesson(module.id, topic.id, unit.id, 'up')}
                                        disabled={uIdx === 0}
                                        className={`p-1 rounded cursor-pointer ${
                                          isSelected ? 'hover:bg-indigo-700 text-indigo-100' : 'hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400'
                                        }`}
                                        title="Move Up"
                                      >
                                        <ChevronUp className="w-3.5 h-3.5" />
                                      </button>

                                      <button
                                        onClick={() => moveLesson(module.id, topic.id, unit.id, 'down')}
                                        disabled={uIdx === topic.learningUnits.length - 1}
                                        className={`p-1 rounded cursor-pointer ${
                                          isSelected ? 'hover:bg-indigo-700 text-indigo-100' : 'hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400'
                                        }`}
                                        title="Move Down"
                                      >
                                        <ChevronDown className="w-3.5 h-3.5" />
                                      </button>

                                      <button
                                        onClick={() => duplicateLesson(module.id, topic.id, unit)}
                                        className={`p-1 rounded cursor-pointer ${
                                          isSelected ? 'hover:bg-indigo-700 text-indigo-100' : 'hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400'
                                        }`}
                                        title="Duplicate"
                                      >
                                        <Copy className="w-3 h-3" />
                                      </button>

                                      <button
                                        onClick={() => deleteLesson(module.id, topic.id, unit.id, unit.title)}
                                        className={`p-1 rounded cursor-pointer ${
                                          isSelected ? 'hover:bg-rose-700 text-rose-100' : 'hover:bg-rose-50 dark:hover:bg-rose-950/40 text-rose-500'
                                        }`}
                                        title="Delete Lesson"
                                      >
                                        <Trash2 className="w-3 h-3" />
                                      </button>
                                    </div>
                                  </div>
                                );
                              })}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* RIGHT COLUMN: MAIN LESSON EDITOR & LIVE PREVIEW WORKSPACE */}
        <div className="lg:col-span-8 bg-white/95 dark:bg-slate-900/95 border border-slate-200/80 dark:border-slate-800 rounded-3xl flex flex-col shadow-xs overflow-hidden">
          
          {!selectedLesson ? (
            <div className="flex-1 flex flex-col items-center justify-center p-12 text-center space-y-4 select-none">
              <div className="w-16 h-16 rounded-3xl bg-indigo-50 dark:bg-slate-950 border border-indigo-100 dark:border-slate-800 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                <FileText className="w-8 h-8" />
              </div>
              <div className="space-y-1 max-w-sm">
                <h4 className="font-heading font-extrabold text-sm text-slate-800 dark:text-slate-200">No Lesson Selected</h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-normal font-medium">
                  Select a lesson from the curriculum outline on the left or add a new lesson to start authoring content.
                </p>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col h-full overflow-hidden">
              
              {/* Top Editor Toolbar */}
              <div className="bg-slate-50/80 dark:bg-slate-950/80 border-b border-slate-200/80 dark:border-slate-800 px-5 py-3.5 flex flex-wrap items-center justify-between gap-3 shrink-0 select-none">
                
                <div className="space-y-0.5 min-w-0">
                  <div className="flex items-center gap-2 text-[10px] font-extrabold text-slate-400 dark:text-slate-500 uppercase tracking-wider">
                    <span>Lesson Editor</span>
                    <span>•</span>
                    <span className="text-indigo-600 dark:text-indigo-400 font-bold">
                      📖 ~{currentReadTime} min read ({currentWords} words)
                    </span>
                  </div>
                  <h4 className="font-heading font-extrabold text-sm text-slate-900 dark:text-white truncate max-w-md">
                    {selectedLesson.title}
                  </h4>
                </div>

                <div className="flex items-center gap-2.5 text-xs font-bold">
                  {/* View Mode Switcher */}
                  {activeTab === 'reading' && (
                    <div className="flex items-center bg-slate-200/60 dark:bg-slate-800/80 p-0.5 rounded-xl text-[11px]">
                      <button
                        onClick={() => setPreviewMode('split')}
                        className={`px-2.5 py-1 rounded-lg transition-all cursor-pointer ${
                          previewMode === 'split' ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 font-extrabold shadow-2xs' : 'text-slate-500'
                        }`}
                        title="Side-by-Side Split View"
                      >
                        Split View
                      </button>
                      <button
                        onClick={() => setPreviewMode('editor')}
                        className={`px-2.5 py-1 rounded-lg transition-all cursor-pointer ${
                          previewMode === 'editor' ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 font-extrabold shadow-2xs' : 'text-slate-500'
                        }`}
                        title="Editor Only"
                      >
                        Editor Only
                      </button>
                      <button
                        onClick={() => setPreviewMode('preview')}
                        className={`px-2.5 py-1 rounded-lg transition-all cursor-pointer ${
                          previewMode === 'preview' ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 font-extrabold shadow-2xs' : 'text-slate-500'
                        }`}
                        title="Live Preview Only"
                      >
                        Preview Only
                      </button>
                    </div>
                  )}

                  {/* Save Status & Button */}
                  <span className={`text-[11px] font-semibold ${
                    saveStatus === 'saving' ? 'text-indigo-500 animate-pulse' : saveStatus === 'saved' ? 'text-emerald-500' : isDirty ? 'text-amber-500' : 'text-slate-400'
                  }`}>
                    {saveStatus === 'saving' ? 'Saving...' : saveStatus === 'saved' ? 'Saved ✓' : isDirty ? 'Unsaved' : 'Autosaved'}
                  </span>

                  {/* AI Lesson Draft Button */}
                  <button
                    type="button"
                    onClick={handleAiAutofillLesson}
                    disabled={isAutofillingLesson || !selectedLesson?.title || selectedLesson.title.trim().length < 3}
                    className="py-1.5 px-3 bg-indigo-50 hover:bg-indigo-100 dark:bg-indigo-950/70 dark:hover:bg-indigo-900 border border-indigo-200 dark:border-indigo-800 text-indigo-600 dark:text-indigo-300 rounded-xl text-xs font-bold flex items-center gap-1.5 cursor-pointer shadow-3xs transition-all disabled:opacity-40"
                    title="Auto-generate complete markdown lesson draft based on title"
                  >
                    <Sparkles className={`w-3.5 h-3.5 text-amber-500 ${isAutofillingLesson ? 'animate-spin' : ''}`} />
                    <span>{isAutofillingLesson ? 'Drafting with AI...' : '✨ AI Draft Content'}</span>
                  </button>

                  <button
                    onClick={handleManualSave}
                    className="py-1.5 px-3.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 cursor-pointer shadow-xs transition-all"
                  >
                    <Save className="w-3.5 h-3.5" />
                    <span>Save Lesson</span>
                  </button>
                </div>
              </div>

              {/* Editor Tabs Switcher */}
              <div className="flex bg-slate-50/40 dark:bg-slate-950/40 border-b border-slate-200/60 dark:border-slate-800 text-xs font-bold overflow-x-auto gap-1 px-4 py-1.5 scrollbar-none select-none shrink-0">
                {[
                  { id: 'reading', label: '📖 Reading Notes (Markdown)' },
                  { id: 'overview', label: '⚙️ Details & Module Placement' },
                  { id: 'video', label: '🎥 Video Stream' },
                  { id: 'resources', label: '📎 Resources' },
                  { id: 'quiz', label: '❓ Quiz' },
                  { id: 'assignment', label: '📝 Assignment' },
                  { id: 'practice-lab', label: '💻 Practice Lab' }
                ].map(tab => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id as any)}
                    className={`py-1.5 px-3 rounded-xl cursor-pointer transition-all whitespace-nowrap shrink-0 ${
                      activeTab === tab.id
                        ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 border border-slate-200/80 dark:border-slate-700 shadow-3xs'
                        : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                    }`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* TAB 1: READING NOTES & LIVE MARKDOWN PREVIEW */}
              {activeTab === 'reading' && (
                <div className="flex-1 flex flex-col min-h-0 overflow-hidden p-4 space-y-3">
                  
                  {/* Markdown Formatting Toolbar */}
                  <div className="flex flex-wrap items-center gap-1 p-1.5 bg-slate-100/80 dark:bg-slate-800/80 rounded-2xl border border-slate-200/60 dark:border-slate-700/80 select-none shrink-0 text-xs">
                    <button
                      type="button"
                      onClick={() => insertMarkdown('h2')}
                      className="py-1 px-2 bg-white dark:bg-slate-900 rounded-lg font-bold hover:bg-slate-50 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700"
                    >
                      H2 Heading
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('h3')}
                      className="py-1 px-2 bg-white dark:bg-slate-900 rounded-lg font-bold hover:bg-slate-50 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700"
                    >
                      H3 Heading
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('bold')}
                      className="py-1 px-2 bg-white dark:bg-slate-900 rounded-lg font-bold hover:bg-slate-50 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700"
                    >
                      Bold
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('italic')}
                      className="py-1 px-2 bg-white dark:bg-slate-900 rounded-lg font-bold hover:bg-slate-50 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700"
                    >
                      Italic
                    </button>

                    <div className="w-px h-4 bg-slate-300 dark:bg-slate-700 mx-1" />

                    <button
                      type="button"
                      onClick={() => insertMarkdown('code-js')}
                      className="py-1 px-2 bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 rounded-lg font-bold border border-indigo-200 dark:border-indigo-800"
                    >
                      JS Code
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('code-py')}
                      className="py-1 px-2 bg-sky-50 dark:bg-sky-950/60 text-sky-600 dark:text-sky-400 rounded-lg font-bold border border-sky-200 dark:border-sky-800"
                    >
                      Python Code
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('code-sql')}
                      className="py-1 px-2 bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 rounded-lg font-bold border border-emerald-200 dark:border-emerald-800"
                    >
                      SQL Query
                    </button>

                    <div className="w-px h-4 bg-slate-300 dark:bg-slate-700 mx-1" />

                    <button
                      type="button"
                      onClick={() => insertMarkdown('tip')}
                      className="py-1 px-2 bg-amber-50 dark:bg-amber-950/60 text-amber-600 dark:text-amber-400 rounded-lg font-bold border border-amber-200 dark:border-amber-800"
                    >
                      💡 Tip Callout
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('note')}
                      className="py-1 px-2 bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 rounded-lg font-bold border border-blue-200 dark:border-blue-800"
                    >
                      📌 Note Callout
                    </button>
                    <button
                      type="button"
                      onClick={() => insertMarkdown('warning')}
                      className="py-1 px-2 bg-rose-50 dark:bg-rose-950/60 text-rose-600 dark:text-rose-400 rounded-lg font-bold border border-rose-200 dark:border-rose-800"
                    >
                      ⚠️ Warning Callout
                    </button>

                    <div className="w-px h-4 bg-slate-300 dark:bg-slate-700 mx-1" />

                    <button
                      type="button"
                      onClick={() => insertMarkdown('table')}
                      className="py-1 px-2 bg-white dark:bg-slate-900 rounded-lg font-bold hover:bg-slate-50 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700"
                    >
                      Table
                    </button>
                  </div>

                  {/* Split Panes / Single Pane */}
                  <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-4 min-h-0 overflow-hidden">
                    
                    {/* Left: Raw Markdown Editor */}
                    {(previewMode === 'split' || previewMode === 'editor') && (
                      <div className={`flex flex-col h-full min-h-0 ${previewMode === 'editor' ? 'col-span-2' : ''}`}>
                        <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1 flex items-center justify-between">
                          <span>Raw Markdown Editor</span>
                          <span>{currentWords} words • ~{currentReadTime}m read</span>
                        </div>
                        <textarea
                          ref={textareaRef}
                          value={selectedLesson.readingContent || ''}
                          onChange={(e) => handleInputChange('readingContent', e.target.value)}
                          placeholder="Write rich markdown course notes here with headings, code blocks, and callouts..."
                          className="w-full flex-1 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 rounded-2xl p-4 focus:outline-hidden font-mono text-xs leading-relaxed resize-none overflow-y-auto shadow-inner"
                        />
                      </div>
                    )}

                    {/* Right: Real-time Live Rendered Preview Pane */}
                    {(previewMode === 'split' || previewMode === 'preview') && (
                      <div className={`flex flex-col h-full min-h-0 ${previewMode === 'preview' ? 'col-span-2' : ''}`}>
                        <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1 flex items-center justify-between">
                          <span>Student-Facing Live Preview</span>
                          <span className="text-emerald-500">Live Rendered</span>
                        </div>
                        <div className="w-full flex-1 bg-white dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 overflow-y-auto shadow-inner">
                          <MarkdownContent content={selectedLesson.readingContent || '_No content written yet._'} />
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* TAB 2: OVERVIEW & MODULE PLACEMENT */}
              {activeTab === 'overview' && (
                <div className="flex-1 overflow-y-auto p-5 text-xs font-semibold space-y-5">
                  
                  {/* Module Assignment Selector */}
                  <div className="p-4 bg-indigo-50/50 dark:bg-indigo-950/30 border border-indigo-100 dark:border-indigo-900/60 rounded-2xl space-y-3">
                    <div className="flex items-center justify-between">
                      <label className="text-indigo-900 dark:text-indigo-300 font-bold block">
                        Assigned Module Placement
                      </label>
                      <button
                        type="button"
                        onClick={() => setIsCreatingNewMod(!isCreatingNewMod)}
                        className="text-indigo-600 dark:text-indigo-400 hover:underline font-bold text-[11px]"
                      >
                        {isCreatingNewMod ? 'Choose Existing Module' : '+ Create New Module'}
                      </button>
                    </div>

                    {!isCreatingNewMod ? (
                      <select
                        value={activeModuleId || ''}
                        onChange={(e) => handleMoveLessonToModule(e.target.value)}
                        className="w-full bg-white dark:bg-slate-900 border border-indigo-200 dark:border-indigo-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden font-bold cursor-pointer"
                      >
                        {activeCourse.modules?.map((m) => (
                          <option key={m.id} value={m.id} className="dark:bg-slate-900">
                            {m.title}
                          </option>
                        ))}
                      </select>
                    ) : (
                      <div className="flex gap-2">
                        <input
                          type="text"
                          placeholder="New Module Title (e.g. Module 5: Advanced Topics)"
                          value={newModTitleInput}
                          onChange={(e) => setNewModTitleInput(e.target.value)}
                          className="flex-1 bg-white dark:bg-slate-900 border border-indigo-200 dark:border-indigo-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden"
                        />
                        <button
                          type="button"
                          onClick={handleCreateModuleAndMove}
                          className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold cursor-pointer shrink-0"
                        >
                          Create & Move
                        </button>
                      </div>
                    )}
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-slate-500 dark:text-slate-400">Lesson Title</label>
                        <button
                          type="button"
                          onClick={handleAiAutofillLesson}
                          disabled={isAutofillingLesson || !selectedLesson.title || selectedLesson.title.trim().length < 3}
                          className="text-[10px] text-indigo-600 dark:text-indigo-400 font-bold hover:underline flex items-center gap-1 cursor-pointer disabled:opacity-40"
                        >
                          <Sparkles className="w-3 h-3 text-amber-400" />
                          <span>{isAutofillingLesson ? 'Drafting...' : '✨ Autofill Content'}</span>
                        </button>
                      </div>
                      <input
                        type="text"
                        value={selectedLesson.title}
                        onChange={(e) => handleInputChange('title', e.target.value)}
                        className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden"
                      />
                    </div>
                    <div>
                      <label className="text-slate-500 dark:text-slate-400 block mb-1">Estimated Duration</label>
                      <input
                        type="text"
                        value={selectedLesson.duration}
                        onChange={(e) => handleInputChange('duration', e.target.value)}
                        className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="text-slate-500 dark:text-slate-400 block mb-1">Lesson Summary / Description</label>
                    <textarea
                      value={selectedLesson.description}
                      onChange={(e) => handleInputChange('description', e.target.value)}
                      rows={3}
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-slate-500 dark:text-slate-400 block mb-1">Content Delivery Type</label>
                      <select
                        value={selectedLesson.type}
                        onChange={(e) => handleInputChange('type', e.target.value)}
                        className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden cursor-pointer"
                      >
                        <option value="Reading">Reading</option>
                        <option value="Video">Video</option>
                        <option value="Quiz">Quiz</option>
                        <option value="Assignment">Assignment</option>
                      </select>
                    </div>

                    <div>
                      <label className="text-slate-500 dark:text-slate-400 block mb-1">Order Position</label>
                      <input
                        type="number"
                        value={selectedLesson.order || 1}
                        onChange={(e) => handleInputChange('order', parseInt(e.target.value, 10))}
                        className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden"
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 3: VIDEO */}
              {activeTab === 'video' && (
                <div className="flex-1 overflow-y-auto p-5 text-xs font-semibold space-y-4">
                  <div>
                    <label className="text-slate-500 dark:text-slate-400 block mb-1">Video Stream URL (YouTube / Vimeo / CDN)</label>
                    <input
                      type="text"
                      value={selectedLesson.videoUrl || ''}
                      onChange={(e) => handleInputChange('videoUrl', e.target.value)}
                      placeholder="https://www.youtube.com/watch?v=..."
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-2.5 focus:outline-hidden"
                    />
                  </div>
                </div>
              )}

              {/* TAB 4: RESOURCES */}
              {activeTab === 'resources' && (
                <div className="flex-1 overflow-y-auto p-5 text-xs font-semibold space-y-4">
                  <div className="space-y-2">
                    <label className="text-slate-500 dark:text-slate-400 block">Attached Resource Files</label>
                    
                    {!(selectedLesson as any).resources || (selectedLesson as any).resources.length === 0 ? (
                      <p className="text-[11px] text-slate-400 italic">No resources attached to this lesson.</p>
                    ) : (
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        {((selectedLesson as any).resources as ResourceItem[]).map((res) => (
                          <div key={res.id} className="p-3 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl flex items-center justify-between gap-3">
                            <div className="flex items-center gap-2 min-w-0">
                              <FileCode className="w-4 h-4 text-indigo-500 shrink-0" />
                              <div className="min-w-0">
                                <span className="block truncate text-slate-800 dark:text-slate-200 font-bold">{res.name}</span>
                                <span className="text-[10px] text-slate-400 font-semibold">{res.category} • {res.fileSize}</span>
                              </div>
                            </div>
                            <button onClick={() => deleteResource(res.id)} className="p-1 hover:bg-rose-50 text-rose-600 rounded cursor-pointer">
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Attach resource form */}
                  <div className="p-4 bg-slate-50/50 dark:bg-slate-950/50 border border-slate-200 dark:border-slate-800 rounded-2xl space-y-3">
                    <span className="font-bold text-slate-800 dark:text-slate-200 block text-xs">Attach New Resource</span>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                      <input
                        type="text"
                        placeholder="File Name (e.g. notes.pdf)"
                        value={newResourceName}
                        onChange={(e) => setNewResourceName(e.target.value)}
                        className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-lg p-2 focus:outline-hidden"
                      />
                      <select
                        value={newResourceCat}
                        onChange={(e) => setNewResourceCat(e.target.value as any)}
                        className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-lg p-2 focus:outline-hidden cursor-pointer"
                      >
                        <option value="PDF">PDF Document</option>
                        <option value="DOCX">Word Document</option>
                        <option value="ZIP">ZIP Archive</option>
                        <option value="Source Code">Source Code File</option>
                        <option value="External Link">External URL Link</option>
                      </select>
                      <button
                        type="button"
                        onClick={addResourceToLesson}
                        className="bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-lg py-2 cursor-pointer shadow-sm text-center"
                      >
                        Attach Resource
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 5: QUIZ */}
              {activeTab === 'quiz' && (
                <div className="flex-1 overflow-y-auto p-5 text-xs font-semibold space-y-4">
                  <div className="space-y-2">
                    <label className="text-slate-500 dark:text-slate-400 block">Assessment Questions</label>
                    <p className="text-slate-400 text-[11px]">Attach multiple-choice assessment questions for this unit.</p>
                  </div>
                </div>
              )}

              {/* TAB 6: ASSIGNMENT */}
              {activeTab === 'assignment' && (
                <div className="flex-1 overflow-y-auto p-5 text-xs font-semibold space-y-4">
                  <div>
                    <label className="text-slate-500 dark:text-slate-400 block mb-1">Assignment Problem Statement</label>
                    <textarea
                      value={selectedLesson.assignmentInstructions || ''}
                      onChange={(e) => handleInputChange('assignmentInstructions', e.target.value)}
                      rows={6}
                      placeholder="Write assignment requirements and instructions..."
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-3 focus:outline-hidden font-mono text-xs"
                    />
                  </div>
                </div>
              )}

              {/* TAB 7: PRACTICE LAB */}
              {activeTab === 'practice-lab' && (
                <div className="flex-1 overflow-y-auto p-5 text-xs font-semibold space-y-4">
                  <div>
                    <label className="text-slate-500 dark:text-slate-400 block mb-1">Coding Challenge Starter Template</label>
                    <textarea
                      value={((selectedLesson as any).practiceLabChallenge?.starterCode) || ''}
                      onChange={(e) => {
                        const prevCh = (selectedLesson as any).practiceLabChallenge || {};
                        handleInputChange('practiceLabChallenge' as any, { ...prevCh, starterCode: e.target.value });
                      }}
                      rows={8}
                      placeholder="function solve() {\n  // Starter code\n}"
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white rounded-xl p-3 focus:outline-hidden font-mono text-xs"
                    />
                  </div>
                </div>
              )}

            </div>
          )}
        </div>
      </div>

      {/* DISCARD CHANGES CONFIRMATION MODAL */}
      {showDiscardModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs animate-in fade-in duration-150">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 max-w-sm w-full shadow-2xl space-y-4">
            <div className="w-12 h-12 rounded-2xl bg-amber-50 dark:bg-amber-950/60 border border-amber-200 dark:border-amber-800 flex items-center justify-center text-amber-500">
              <AlertTriangle className="w-6 h-6" />
            </div>

            <div className="space-y-1">
              <h4 className="font-heading font-extrabold text-base text-slate-900 dark:text-white">
                Unsaved Changes
              </h4>
              <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-medium">
                You have unsaved edits in this lesson. Are you sure you want to discard them and switch lessons?
              </p>
            </div>

            <div className="flex items-center justify-end gap-2.5 pt-2">
              <button
                onClick={() => {
                  setShowDiscardModal(false);
                  setPendingSelection(null);
                }}
                className="px-4 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold rounded-xl text-xs cursor-pointer"
              >
                Keep Editing
              </button>

              <button
                onClick={confirmDiscardChanges}
                className="px-4 py-2 bg-rose-600 hover:bg-rose-500 text-white font-bold rounded-xl text-xs cursor-pointer shadow-sm"
              >
                Discard Changes
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default AdminContentManagement;
